apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: workshop-02
spec:
  containers:
    - name: curl002
      image: curlimages/curl
      command: ['sh', '-c', 'while true; do sleep 5; done']
    - name: curl003
      image: curlimages/curl
      command: ['sh', '-c', 'while true; do sleep 5; done']
    - name: curl004
      image: curlimages/curl
      command: ['sh', '-c', 'while true; do sleep 5; done']
