apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-05
  name: resource-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['/bin/sh','-c','while true; do sleep 5; done']
      resources:
        requests:
          cpu: '250m'
          memory: '128Mi'
        limits:
          cpu: '500m'
          memory: '256Mi'