apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-05
  name: liveness-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 5; done']
      livenessProbe:
        exec:
          command: ['echo', 'Hello, World!']
        initialDelaySeconds: 5
        periodSeconds: 5