apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-05
  name: liveness-pod-http
spec:
  containers:
    - name: nginx
      image: nginx:latest
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5