apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-05
  name: startup-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 30
        periodSeconds: 10