apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-05
  name: readiness-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5