apiVersion: v1
kind: Namespace
metadata:
  name: workshop-03
  labels:
    name: workshop-03
    module: workshop-03
---
apiVersion: v1
kind: Pod
metadata:
  name: echo-pod
  namespace: workshop-03
  labels:
    app: echo-pod-app
spec:
  containers:
    - name: echo
      image: ealen/echo-server:latest
    - name: netshoot
      image: nicolaka/netshoot
      command: ['bash', '-c', 'while true; do sleep 5; done']
      securityContext:
        privileged: true