apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-06
  name: always-pod
spec:
  restartPolicy: Always
  containers:
    - name: busybox
      image: busybox
      command: [ 'sh', '-c', 'sleep 10' ]