apiVersion: v1
kind: ConfigMap
metadata:
  namespace: workshop-04
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }
    http {
        server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            auth_basic "Secure Site";
            auth_basic_user_file conf/.htpasswd;
        }
    }

---
apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-04
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
        - name: htpasswd-volume
          mountPath: /etc/nginx/conf
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
    - name: htpasswd-volume
      secret:
        secretName: nginx-htpasswd
---
apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-04
  name: curl-pod
spec:
  containers:
    - name: curl-pod
      image: curlimages/curl
      command: [ 'sh', '-c', 'while true; do sleep 5; done' ]