apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-07
  name: sidecar-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do now=$(date);echo logs time $now >> /logs/output.log; sleep 5; done']
      volumeMounts:
        - name: sharedvol
          mountPath: /logs
    - name: sidecar
      image: busybox
      command: ['sh', '-c', 'tail -f /logs/output.log']
      volumeMounts:
        - name: sharedvol
          mountPath: /logs
  volumes:
    - name: sharedvol
      emptyDir: {}