apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-07
  name: shipping-backend
  labels:
    app: shipping-svc
spec:
  containers:
    - name: nginx
      image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  namespace: workshop-07
  name: shipping-svc
spec:
  selector:
    app: shipping-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  namespace: workshop-07
  name: shipping-web
spec:
  containers:
    - name: nginx
      image: nginx:latest
  initContainers:
    - name: shipping-svc-check
      image: curlimages/curl
      command: ['sh', '-c', 'until curl -s -f -o /dev/null "http://shipping-svc"; do echo waiting for shipping-svc; sleep 5; done']
