apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
  labels:
    type: node
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/data
