apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: workshop-11
  name: host-pvc
spec:
  storageClassName: localdisk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: host-pv