apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-pv
  labels:
    type: cluster
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/k3dvol"