apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: workshop-11
  name: k3d-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: k3d-pv