#do not remember to change the owner of the folder with command "sudo chown -R 1000:1000 mysql-data" and "sudo chmod 777 mysql-data"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/k3dvol/mysql-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress-ns
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: mysql-pv