apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/k3dvol/wp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress-ns
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: wp-pv