apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workshop-09
  name: my-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
